import React from "react";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import { SignOutButton, useUser, SignInButton } from "@clerk/nextjs";
import Image from "next/image";
import type { RouterOutputs } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import LoadingSpinner from "~/components/loading";
import toast from "react-hot-toast";

const SinglePostPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">Post page</main>
    </>
  );
};

export default SinglePostPage;
